services:
  web:
    image: httpd:latest
    networks:
      rede_test:
        aliases:
          - www.proba.lan
          - proba.lan

  cliente:
    build: cliente
    networks:
      - rede_test
    environment:
    - DISPLAY=${DISPLAY}
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix

networks:
  rede_test: